const TextContent = (() => {
  const classicTexts = {
    easy: [
      "The best time to plant a tree was twenty years ago. The second best time is now.",
      "Stay hungry, stay foolish.",
      "Talk is cheap. Show me the code.",
      "First, solve the problem. Then, write the code.",
      "Simplicity is the soul of efficiency.",
      "The only way to do great work is to love what you do.",
      "Life is what happens when you are busy making other plans.",
      "In the end we only regret the chances we did not take.",
      "Be the change that you wish to see in the world today.",
      "Do what you can with what you have where you are right now.",
      "Every moment is a fresh beginning for those who dare to try.",
      "What we think we become. What we feel we attract in life.",
      "Believe you can and you are already halfway there my friend.",
      "The mind is everything. What you think you become over time.",
      "Actions speak louder than words. Let your work do the talking.",
      "A ship in harbor is safe but that is not what ships are built for.",
      "Well done is better than well said every single time.",
      "The best way to predict the future is to create it yourself.",
      "Keep it simple. Keep it clear. Keep it moving forward.",
      "Dream big. Start small. Act now. Keep going no matter what.",
      "It does not matter how slowly you go as long as you do not stop.",
      "You miss every shot you do not take so take the shot today.",
      "The purpose of our lives is to be happy and to help others grow.",
      "The journey of a thousand miles begins with a single step forward.",
      "Make each day your masterpiece and the years will take care of themselves."
    ],
    medium: [
      "Any fool can write code that a computer can understand. Good programmers write code that humans can understand.",
      "The most dangerous phrase in the language is: we have always done it this way.",
      "Programming is not about typing, it is about thinking. But you still need to type fast to keep up with your thoughts.",
      "In the middle of difficulty lies opportunity. The important thing is not to stop questioning. Curiosity has its own reason for existing.",
      "Success is not final and failure is not fatal. It is the courage to continue that counts in the grand scheme of things.",
      "The greatest glory in living lies not in never falling, but in rising every time we fall. That is the mark of true strength.",
      "You have power over your mind, not outside events. Realize this and you will find great strength within yourself.",
      "The only impossible journey is the one you never begin. Take that first step and the path will reveal itself to you.",
      "It is during our darkest moments that we must focus to see the light. The light is always there waiting to be found.",
      "Tell me and I forget. Teach me and I remember. Involve me and I learn. That is the true nature of education and growth.",
      "Many of life's failures are people who did not realize how close they were to success when they gave up trying.",
      "The future belongs to those who believe in the beauty of their dreams and have the courage to pursue them relentlessly.",
      "Education is the most powerful weapon which you can use to change the world and shape a better tomorrow for everyone.",
      "I have not failed. I have just found ten thousand ways that do not work. Each attempt brings me closer to the answer.",
      "Happiness is not something ready made. It comes from your own actions and the choices you make every single day.",
      "The only limit to our realization of tomorrow will be our doubts of today. Let us move forward with strong and active faith.",
      "Life is really simple but we insist on making it complicated. Simplicity is the ultimate sophistication in all things.",
      "The secret of getting ahead is getting started. The secret of getting started is breaking complex tasks into small manageable ones.",
      "Perfection is achieved not when there is nothing more to add, but when there is nothing left to take away from the design.",
      "The computer was born to solve problems that did not exist before. Now it solves problems we never knew we had in the first place.",
      "Before software can be reusable it first has to be usable. Focus on making it work well before making it work everywhere.",
      "Measuring programming progress by lines of code is like measuring aircraft building progress by weight. It misses the entire point.",
      "The best error message is the one that never shows up. Design your systems so that users never encounter failure states.",
      "Code is like humor. When you have to explain it, it is bad. Write code that speaks for itself and needs no commentary.",
      "Walking on water and developing software from a specification are easy if both are frozen solid and never need to change."
    ],
    hard: [
      "It is not the critic who counts; not the man who points out how the strong man stumbles, or where the doer of deeds could have done them better. The credit belongs to the man who is actually in the arena, whose face is marred by dust and sweat and blood.",
      "We hold these truths to be self-evident, that all men are created equal, that they are endowed by their Creator with certain unalienable Rights, that among these are Life, Liberty and the pursuit of Happiness.",
      "In a hole in the ground there lived a hobbit. Not a nasty, dirty, wet hole, filled with the ends of worms and an oozy smell, nor yet a dry, bare, sandy hole with nothing in it to sit down on or to eat: it was a hobbit-hole, and that means comfort.",
      "The only thing we have to fear is fear itself; nameless, unreasoning, unjustified terror which paralyzes needed efforts to convert retreat into advance. In every dark hour of our national life a leadership of frankness and vigor has met with understanding.",
      "Two roads diverged in a wood, and I took the one less traveled by, and that has made all the difference. I shall be telling this with a sigh somewhere ages and ages hence, when I look back on the choices I have made.",
      "It was the best of times, it was the worst of times, it was the age of wisdom, it was the age of foolishness, it was the epoch of belief, it was the epoch of incredulity, it was the season of Light, it was the season of Darkness.",
      "To be, or not to be, that is the question: Whether it is nobler in the mind to suffer the slings and arrows of outrageous fortune, or to take arms against a sea of troubles, and by opposing end them.",
      "The world is a book, and those who do not travel read only one page. Every journey teaches us something new about ourselves; every destination reveals a truth we could not have discovered by staying home and wondering.",
      "All that is gold does not glitter, not all those who wander are lost; the old that is strong does not wither, deep roots are not reached by the frost. From the ashes a fire shall be woken, a light from the shadows shall spring.",
      "There is nothing either good or bad, but thinking makes it so. The mind is its own place, and in itself can make a heaven of hell, a hell of heaven. What matters is not what happens to us, but how we interpret and respond to it.",
      "Debugging is twice as hard as writing the code in the first place. Therefore, if you write the code as cleverly as possible, you are, by definition, not smart enough to debug it. Always favor clarity over cleverness in your work.",
      "The question of whether a computer can think is no more interesting than the question of whether a submarine can swim. What matters is what it can accomplish, not whether its methods mirror our own biological processes.",
      "Any sufficiently advanced technology is indistinguishable from magic. What was once considered impossible becomes routine, and what we now consider miraculous will someday be taken for granted by future generations.",
      "People who are really serious about software should make their own hardware. The greatest innovations come from controlling the entire stack, from the silicon to the interface that the user sees and touches.",
      "The art of programming is the art of organizing complexity; of mastering multitude and avoiding its bastard chaos as effectively as possible. Structure and discipline are the foundations upon which great systems are built.",
      "In theory, there is no difference between theory and practice. But in practice, there is. The gap between what we plan and what actually happens is where all the interesting engineering challenges live.",
      "The real danger is not that computers will begin to think like men, but that men will begin to think like computers. We must preserve the creative, intuitive, and empathetic qualities that make us uniquely human.",
      "We can only see a short distance ahead, but we can see plenty there that needs to be done. The challenge is not in identifying problems; it is in summoning the will and the resources to solve them systematically.",
      "I think that it is extraordinarily important that we in computer science keep fun in computing. When it started out, it was an awful lot of fun. Of course, the paying customers got shafted every now and then.",
      "The function of good software is to make the complex appear to be simple. Behind every intuitive interface lies a mountain of careful engineering, thoughtful design decisions, and thousands of hours of testing."
    ]
  };

  const codeSnippets = {
    javascript: [
      `function fibonacci(n) {\n  if (n <= 1) return n;\n  return fibonacci(n - 1) + fibonacci(n - 2);\n}`,
      `const fetchData = async (url) => {\n  const response = await fetch(url);\n  const data = await response.json();\n  return data;\n};`,
      `const debounce = (fn, delay) => {\n  let timer;\n  return (...args) => {\n    clearTimeout(timer);\n    timer = setTimeout(() => fn(...args), delay);\n  };\n};`,
      `class EventEmitter {\n  constructor() {\n    this.events = {};\n  }\n  on(event, callback) {\n    if (!this.events[event]) {\n      this.events[event] = [];\n    }\n    this.events[event].push(callback);\n  }\n  emit(event, ...args) {\n    const handlers = this.events[event];\n    if (handlers) {\n      handlers.forEach(fn => fn(...args));\n    }\n  }\n}`,
      `const flattenArray = (arr) => {\n  return arr.reduce((flat, item) => {\n    return flat.concat(\n      Array.isArray(item) ? flattenArray(item) : item\n    );\n  }, []);\n};`,
      `document.addEventListener("DOMContentLoaded", () => {\n  const buttons = document.querySelectorAll(".btn");\n  buttons.forEach(btn => {\n    btn.addEventListener("click", (e) => {\n      e.target.classList.toggle("active");\n    });\n  });\n});`,
      `function deepClone(obj) {\n  if (obj === null || typeof obj !== "object") {\n    return obj;\n  }\n  const clone = Array.isArray(obj) ? [] : {};\n  for (const key in obj) {\n    clone[key] = deepClone(obj[key]);\n  }\n  return clone;\n}`,
      `const numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];\nconst evens = numbers.filter(n => n % 2 === 0);\nconst doubled = evens.map(n => n * 2);\nconst sum = doubled.reduce((acc, n) => acc + n, 0);`,
      `const { name, age, ...rest } = user;\nconst fullName = \`\${name.first} \${name.last}\`;\nconst profile = { fullName, age, ...rest };\nconst tags = [...profile.tags, "active"];`,
      `async function getUserPosts(userId) {\n  try {\n    const res = await fetch(\`/api/users/\${userId}/posts\`);\n    if (!res.ok) {\n      throw new Error(\`HTTP error: \${res.status}\`);\n    }\n    const posts = await res.json();\n    return posts.filter(p => p.published);\n  } catch (error) {\n    console.error("Failed to fetch posts:", error);\n    return [];\n  }\n}`,
      `const throttle = (fn, limit) => {\n  let inThrottle = false;\n  return (...args) => {\n    if (!inThrottle) {\n      fn(...args);\n      inThrottle = true;\n      setTimeout(() => {\n        inThrottle = false;\n      }, limit);\n    }\n  };\n};`,
      `class LinkedList {\n  constructor() {\n    this.head = null;\n    this.size = 0;\n  }\n  add(value) {\n    const node = { value, next: null };\n    if (!this.head) {\n      this.head = node;\n    } else {\n      let current = this.head;\n      while (current.next) {\n        current = current.next;\n      }\n      current.next = node;\n    }\n    this.size++;\n  }\n}`,
      `const observer = new IntersectionObserver(\n  (entries) => {\n    entries.forEach((entry) => {\n      if (entry.isIntersecting) {\n        entry.target.classList.add("visible");\n        observer.unobserve(entry.target);\n      }\n    });\n  },\n  { threshold: 0.1 }\n);`
    ],
    python: [
      `def binary_search(arr, target):\n    low, high = 0, len(arr) - 1\n    while low <= high:\n        mid = (low + high) // 2\n        if arr[mid] == target:\n            return mid\n        elif arr[mid] < target:\n            low = mid + 1\n        else:\n            high = mid - 1\n    return -1`,
      `def quicksort(arr):\n    if len(arr) <= 1:\n        return arr\n    pivot = arr[len(arr) // 2]\n    left = [x for x in arr if x < pivot]\n    middle = [x for x in arr if x == pivot]\n    right = [x for x in arr if x > pivot]\n    return quicksort(left) + middle + quicksort(right)`,
      `class Stack:\n    def __init__(self):\n        self.items = []\n\n    def push(self, item):\n        self.items.append(item)\n\n    def pop(self):\n        if not self.is_empty():\n            return self.items.pop()\n        return None\n\n    def is_empty(self):\n        return len(self.items) == 0`,
      `def flatten(lst):\n    result = []\n    for item in lst:\n        if isinstance(item, list):\n            result.extend(flatten(item))\n        else:\n            result.append(item)\n    return result`,
      `with open("data.txt", "r") as file:\n    lines = file.readlines()\n    for line in lines:\n        words = line.strip().split()\n        if len(words) > 0:\n            print(f"Line: {words[0]}")`,
      `def memoize(func):\n    cache = {}\n    def wrapper(*args):\n        if args not in cache:\n            cache[args] = func(*args)\n        return cache[args]\n    return wrapper`,
      `squares = [x ** 2 for x in range(20) if x % 2 == 0]\nword_lengths = {word: len(word) for word in words}\nflattened = [item for sublist in matrix for item in sublist]\nfiltered = {k: v for k, v in data.items() if v > threshold}`,
      `def fibonacci_gen():\n    a, b = 0, 1\n    while True:\n        yield a\n        a, b = b, a + b\n\nfib = fibonacci_gen()\nfirst_ten = [next(fib) for _ in range(10)]`,
      `class Timer:\n    def __enter__(self):\n        self.start = time.time()\n        return self\n\n    def __exit__(self, exc_type, exc_val, exc_tb):\n        self.elapsed = time.time() - self.start\n        print(f"Elapsed: {self.elapsed:.4f}s")\n        return False`,
      `def validate_email(email: str) -> bool:\n    import re\n    pattern = r"^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\\.[a-zA-Z0-9-.]+$"\n    return bool(re.match(pattern, email))`,
      `class Node:\n    def __init__(self, value, left=None, right=None):\n        self.value = value\n        self.left = left\n        self.right = right\n\n    def inorder(self):\n        result = []\n        if self.left:\n            result.extend(self.left.inorder())\n        result.append(self.value)\n        if self.right:\n            result.extend(self.right.inorder())\n        return result`,
      `try:\n    data = json.loads(raw_input)\n    result = process_data(data)\n    save_to_database(result)\nexcept json.JSONDecodeError as e:\n    logging.error(f"Invalid JSON: {e}")\nexcept DatabaseError as e:\n    logging.error(f"DB error: {e}")\n    raise\nfinally:\n    cleanup_resources()`,
      `from dataclasses import dataclass\nfrom typing import List, Optional\n\n@dataclass\nclass User:\n    name: str\n    email: str\n    age: int\n    roles: List[str]\n    bio: Optional[str] = None\n\n    def is_admin(self) -> bool:\n        return "admin" in self.roles`
    ],
    html: [
      `<nav class="navbar">\n  <div class="logo">\n    <a href="/">TypeRush</a>\n  </div>\n  <ul class="nav-links">\n    <li><a href="/about">About</a></li>\n    <li><a href="/contact">Contact</a></li>\n  </ul>\n</nav>`,
      `<form class="login-form" action="/login" method="POST">\n  <div class="form-group">\n    <label for="email">Email</label>\n    <input type="email" id="email" name="email" required>\n  </div>\n  <div class="form-group">\n    <label for="password">Password</label>\n    <input type="password" id="password" name="password" required>\n  </div>\n  <button type="submit" class="btn">Log In</button>\n</form>`,
      `<section class="hero">\n  <div class="container">\n    <h1 class="hero-title">Welcome to TypeRush</h1>\n    <p class="hero-subtitle">Test your typing speed</p>\n    <div class="hero-actions">\n      <a href="#play" class="btn btn-primary">Play Now</a>\n      <a href="#learn" class="btn btn-secondary">Learn More</a>\n    </div>\n  </div>\n</section>`,
      `<div class="card-grid">\n  <article class="card">\n    <img src="image.jpg" alt="Card image">\n    <div class="card-body">\n      <h3 class="card-title">Title Here</h3>\n      <p class="card-text">Description goes here.</p>\n      <a href="#" class="card-link">Read More</a>\n    </div>\n  </article>\n</div>`,
      `<table class="data-table">\n  <thead>\n    <tr>\n      <th>Name</th>\n      <th>Email</th>\n      <th>Role</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <td>Alice</td>\n      <td>alice@example.com</td>\n      <td>Admin</td>\n    </tr>\n  </tbody>\n</table>`,
      `<header class="site-header">\n  <div class="container">\n    <a href="/" class="brand">\n      <img src="logo.svg" alt="Logo" width="40" height="40">\n      <span class="brand-name">TypeRush</span>\n    </a>\n    <nav class="main-nav" aria-label="Main navigation">\n      <ul>\n        <li><a href="/features">Features</a></li>\n        <li><a href="/pricing">Pricing</a></li>\n        <li><a href="/docs">Docs</a></li>\n      </ul>\n    </nav>\n    <button class="menu-toggle" aria-label="Toggle menu">\n      <span class="hamburger"></span>\n    </button>\n  </div>\n</header>`,
      `<dialog class="modal" id="confirmDialog">\n  <div class="modal-content">\n    <h2 class="modal-title">Confirm Action</h2>\n    <p class="modal-body">Are you sure you want to proceed?</p>\n    <div class="modal-actions">\n      <button class="btn btn-secondary" id="cancelBtn">Cancel</button>\n      <button class="btn btn-danger" id="confirmBtn">Confirm</button>\n    </div>\n  </div>\n</dialog>`,
      `<footer class="site-footer">\n  <div class="container">\n    <div class="footer-grid">\n      <div class="footer-col">\n        <h4>Product</h4>\n        <ul>\n          <li><a href="/features">Features</a></li>\n          <li><a href="/pricing">Pricing</a></li>\n          <li><a href="/changelog">Changelog</a></li>\n        </ul>\n      </div>\n      <div class="footer-col">\n        <h4>Company</h4>\n        <ul>\n          <li><a href="/about">About</a></li>\n          <li><a href="/blog">Blog</a></li>\n          <li><a href="/careers">Careers</a></li>\n        </ul>\n      </div>\n    </div>\n    <p class="copyright">Copyright 2026 TypeRush</p>\n  </div>\n</footer>`,
      `<aside class="sidebar">\n  <div class="sidebar-header">\n    <h3>Dashboard</h3>\n  </div>\n  <ul class="sidebar-nav">\n    <li class="nav-item active">\n      <a href="/dashboard">\n        <svg class="icon"><use href="#icon-home"></use></svg>\n        <span>Home</span>\n      </a>\n    </li>\n    <li class="nav-item">\n      <a href="/settings">\n        <svg class="icon"><use href="#icon-gear"></use></svg>\n        <span>Settings</span>\n      </a>\n    </li>\n  </ul>\n</aside>`,
      `<head>\n  <meta charset="UTF-8">\n  <meta name="viewport" content="width=device-width, initial-scale=1.0">\n  <meta name="description" content="A typing speed game">\n  <meta property="og:title" content="TypeRush">\n  <meta property="og:type" content="website">\n  <meta property="og:image" content="/og-image.png">\n  <link rel="icon" type="image/svg+xml" href="/favicon.svg">\n  <link rel="stylesheet" href="/css/main.css">\n  <title>TypeRush</title>\n</head>`,
      `<ul class="timeline">\n  <li class="timeline-item">\n    <span class="timeline-date">Jan 2024</span>\n    <div class="timeline-content">\n      <h4>Project Started</h4>\n      <p>Initial commit and project setup.</p>\n    </div>\n  </li>\n  <li class="timeline-item">\n    <span class="timeline-date">Mar 2024</span>\n    <div class="timeline-content">\n      <h4>Beta Launch</h4>\n      <p>Released to early testers.</p>\n    </div>\n  </li>\n</ul>`,
      `<fieldset class="form-section">\n  <legend>Shipping Address</legend>\n  <div class="field-row">\n    <label for="street">Street</label>\n    <input type="text" id="street" name="street" required>\n  </div>\n  <div class="field-row field-row--split">\n    <div>\n      <label for="city">City</label>\n      <input type="text" id="city" name="city" required>\n    </div>\n    <div>\n      <label for="zip">ZIP Code</label>\n      <input type="text" id="zip" name="zip" pattern="[0-9]{5}" required>\n    </div>\n  </div>\n</fieldset>`
    ],
    css: [
      `.card {\n  display: flex;\n  flex-direction: column;\n  padding: 1.5rem;\n  border-radius: 12px;\n  background: var(--card-bg);\n  box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);\n  transition: transform 0.2s ease;\n}`,
      `@keyframes fadeIn {\n  from {\n    opacity: 0;\n    transform: translateY(20px);\n  }\n  to {\n    opacity: 1;\n    transform: translateY(0);\n  }\n}\n\n.animate-in {\n  animation: fadeIn 0.4s ease forwards;\n}`,
      `.grid-layout {\n  display: grid;\n  grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));\n  gap: 1.5rem;\n  padding: 2rem;\n  max-width: 1200px;\n  margin: 0 auto;\n}`,
      `:root {\n  --primary: #3b82f6;\n  --secondary: #8b5cf6;\n  --bg: #0f172a;\n  --text: #e2e8f0;\n  --border: #334155;\n}\n\n* {\n  margin: 0;\n  padding: 0;\n  box-sizing: border-box;\n}\n\nbody {\n  font-family: system-ui, sans-serif;\n  background: var(--bg);\n  color: var(--text);\n}`,
      `.btn {\n  display: inline-flex;\n  align-items: center;\n  gap: 0.5rem;\n  padding: 0.75rem 1.5rem;\n  border: none;\n  border-radius: 8px;\n  font-size: 1rem;\n  font-weight: 600;\n  cursor: pointer;\n  transition: all 0.2s ease;\n}\n\n.btn:hover {\n  transform: translateY(-2px);\n  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.3);\n}`,
      `.navbar {\n  display: flex;\n  align-items: center;\n  justify-content: space-between;\n  padding: 1rem 2rem;\n  background: var(--surface);\n  border-bottom: 1px solid var(--border);\n  position: sticky;\n  top: 0;\n  z-index: 100;\n  backdrop-filter: blur(12px);\n}`,
      `.sidebar {\n  width: 260px;\n  height: 100vh;\n  position: fixed;\n  top: 0;\n  left: 0;\n  background: var(--surface);\n  border-right: 1px solid var(--border);\n  display: flex;\n  flex-direction: column;\n  padding: 1.5rem 0;\n  overflow-y: auto;\n}\n\n.sidebar-link {\n  display: flex;\n  align-items: center;\n  gap: 0.75rem;\n  padding: 0.6rem 1.5rem;\n  color: var(--text-secondary);\n  text-decoration: none;\n  transition: background 0.15s ease;\n}\n\n.sidebar-link:hover {\n  background: rgba(255, 255, 255, 0.05);\n}`,
      `@media (max-width: 768px) {\n  .container {\n    padding: 0 1rem;\n  }\n  .hero-title {\n    font-size: 2rem;\n  }\n  .grid {\n    grid-template-columns: 1fr;\n  }\n  .sidebar {\n    display: none;\n  }\n  .nav-links {\n    position: fixed;\n    inset: 0;\n    background: var(--bg);\n    flex-direction: column;\n    align-items: center;\n    justify-content: center;\n    transform: translateX(100%);\n    transition: transform 0.3s ease;\n  }\n  .nav-links.open {\n    transform: translateX(0);\n  }\n}`,
      `.tooltip {\n  position: relative;\n  cursor: help;\n}\n\n.tooltip::after {\n  content: attr(data-tooltip);\n  position: absolute;\n  bottom: calc(100% + 8px);\n  left: 50%;\n  transform: translateX(-50%);\n  padding: 0.5rem 0.75rem;\n  background: var(--surface);\n  color: var(--text);\n  border-radius: 6px;\n  font-size: 0.8rem;\n  white-space: nowrap;\n  opacity: 0;\n  pointer-events: none;\n  transition: opacity 0.2s ease;\n}\n\n.tooltip:hover::after {\n  opacity: 1;\n}`,
      `.skeleton {\n  background: linear-gradient(\n    90deg,\n    var(--border) 25%,\n    rgba(255, 255, 255, 0.05) 50%,\n    var(--border) 75%\n  );\n  background-size: 200% 100%;\n  animation: shimmer 1.5s infinite;\n  border-radius: 4px;\n}\n\n@keyframes shimmer {\n  0% { background-position: 200% 0; }\n  100% { background-position: -200% 0; }\n}`,
      `.dark-theme {\n  --bg: #0a0a0a;\n  --surface: #141414;\n  --card: #1c1c1c;\n  --text: #fafafa;\n  --text-secondary: #a1a1aa;\n  --text-muted: #71717a;\n  --border: #27272a;\n  --primary: #fbbf24;\n  --primary-hover: #f59e0b;\n  --success: #22c55e;\n  --error: #ef4444;\n  --shadow: rgba(0, 0, 0, 0.5);\n}\n\n.light-theme {\n  --bg: #fafafa;\n  --surface: #ffffff;\n  --card: #ffffff;\n  --text: #18181b;\n  --text-secondary: #52525b;\n  --text-muted: #a1a1aa;\n  --border: #e4e4e7;\n  --primary: #d97706;\n  --primary-hover: #b45309;\n  --success: #16a34a;\n  --error: #dc2626;\n  --shadow: rgba(0, 0, 0, 0.1);\n}`,
      `.avatar {\n  width: 48px;\n  height: 48px;\n  border-radius: 50%;\n  object-fit: cover;\n  border: 2px solid var(--border);\n  transition: border-color 0.2s ease;\n}\n\n.avatar:hover {\n  border-color: var(--primary);\n}\n\n.avatar-group {\n  display: flex;\n}\n\n.avatar-group .avatar {\n  margin-left: -12px;\n  box-shadow: 0 0 0 2px var(--bg);\n}\n\n.avatar-group .avatar:first-child {\n  margin-left: 0;\n}`
    ],
    rust: [
      `fn main() {\n    let numbers = vec![1, 2, 3, 4, 5];\n    let sum: i32 = numbers.iter().sum();\n    println!("Sum: {}", sum);\n}`,
      `fn fibonacci(n: u32) -> u32 {\n    match n {\n        0 => 0,\n        1 => 1,\n        _ => fibonacci(n - 1) + fibonacci(n - 2),\n    }\n}`,
      `struct Point {\n    x: f64,\n    y: f64,\n}\n\nimpl Point {\n    fn new(x: f64, y: f64) -> Self {\n        Point { x, y }\n    }\n\n    fn distance(&self, other: &Point) -> f64 {\n        let dx = self.x - other.x;\n        let dy = self.y - other.y;\n        (dx * dx + dy * dy).sqrt()\n    }\n}`,
      `fn bubble_sort(arr: &mut Vec<i32>) {\n    let n = arr.len();\n    for i in 0..n {\n        for j in 0..n - 1 - i {\n            if arr[j] > arr[j + 1] {\n                arr.swap(j, j + 1);\n            }\n        }\n    }\n}`,
      `use std::collections::HashMap;\n\nfn word_count(text: &str) -> HashMap<&str, usize> {\n    let mut map = HashMap::new();\n    for word in text.split_whitespace() {\n        let count = map.entry(word).or_insert(0);\n        *count += 1;\n    }\n    map\n}`,
      `enum Shape {\n    Circle(f64),\n    Rectangle(f64, f64),\n    Triangle(f64, f64),\n}\n\nimpl Shape {\n    fn area(&self) -> f64 {\n        match self {\n            Shape::Circle(r) => std::f64::consts::PI * r * r,\n            Shape::Rectangle(w, h) => w * h,\n            Shape::Triangle(b, h) => 0.5 * b * h,\n        }\n    }\n}`,
      `fn longest<'a>(x: &'a str, y: &'a str) -> &'a str {\n    if x.len() > y.len() {\n        x\n    } else {\n        y\n    }\n}\n\nfn first_word(s: &str) -> &str {\n    let bytes = s.as_bytes();\n    for (i, &item) in bytes.iter().enumerate() {\n        if item == b' ' {\n            return &s[0..i];\n        }\n    }\n    &s[..]\n}`,
      `use std::fs::File;\nuse std::io::{self, BufRead, BufReader};\n\nfn read_lines(path: &str) -> io::Result<Vec<String>> {\n    let file = File::open(path)?;\n    let reader = BufReader::new(file);\n    let mut lines = Vec::new();\n    for line in reader.lines() {\n        lines.push(line?);\n    }\n    Ok(lines)\n}`,
      `trait Summary {\n    fn summarize(&self) -> String;\n    fn preview(&self) -> String {\n        format!("{}...", &self.summarize()[..20])\n    }\n}\n\nstruct Article {\n    title: String,\n    content: String,\n}\n\nimpl Summary for Article {\n    fn summarize(&self) -> String {\n        format!("{}: {}", self.title, self.content)\n    }\n}`,
      `fn parse_number(input: &str) -> Result<i32, String> {\n    input\n        .trim()\n        .parse::<i32>()\n        .map_err(|e| format!("Failed to parse '{}': {}", input, e))\n}\n\nfn divide(a: f64, b: f64) -> Result<f64, String> {\n    if b == 0.0 {\n        Err("Cannot divide by zero".to_string())\n    } else {\n        Ok(a / b)\n    }\n}`,
      `fn apply_twice<F>(f: F, x: i32) -> i32\nwhere\n    F: Fn(i32) -> i32,\n{\n    f(f(x))\n}\n\nfn main() {\n    let double = |x| x * 2;\n    let add_three = |x| x + 3;\n    println!("{}", apply_twice(double, 5));\n    println!("{}", apply_twice(add_three, 5));\n}`,
      `fn capitalize_words(s: &str) -> String {\n    s.split_whitespace()\n        .map(|word| {\n            let mut chars = word.chars();\n            match chars.next() {\n                None => String::new(),\n                Some(c) => {\n                    c.to_uppercase().to_string() + chars.as_str()\n                }\n            }\n        })\n        .collect::<Vec<_>>()\n        .join(" ")\n}`
    ]
  };

  const wordList = [
    // Top 500 most common English words
    "the","be","to","of","and","a","in","that","have","it","for","not","on","with","he",
    "as","you","do","at","this","but","his","by","from","they","we","say","her","she","or",
    "an","will","my","one","all","would","there","their","what","so","up","out","if","about",
    "who","get","which","go","me","when","make","can","like","time","no","just","him","know",
    "take","people","into","year","your","good","some","could","them","see","other","than",
    "then","now","look","only","come","its","over","think","also","back","after","use","two",
    "how","our","work","first","well","way","even","new","want","because","any","these","give",
    "day","most","us","great","between","need","large","often","hand","high","place","hold",
    "here","thing","man","world","life","still","went","should","call","keep","school","never",
    "last","let","thought","city","tree","cross","farm","hard","start","might","story","far",
    "sea","late","run","left","while","press","close","night","real","open","seem","together",
    "next","white","children","begin","got","walk","example","ease","paper","group","always",
    "music","those","both","mark","book","letter","until","mile","river","car","feet","care",
    "second","enough","plain","girl","usual","young","ready","above","ever","red","list","though",
    "feel","talk","bird","soon","body","dog","family","direct","pose","leave","song","measure",
    "door","product","black","short","number","class","wind","question","happen","complete",
    "ship","area","half","rock","order","fire","south","problem","piece","told","knew","pass",
    "since","top","whole","king","space","heard","best","hour","better","true","during","hundred",
    "five","remember","step","early","west","ground","interest","reach","fast","verb",
    "sing","listen","six","table","travel","less","morning","ten","simple","several","vowel",
    "toward","war","lay","against","pattern","slow","center","love","person","money","serve",
    "appear","road","map","rain","rule","govern","pull","cold","notice","voice","unit","power",
    "town","fine","certain","fly","fall","lead","cry","dark","machine","note","wait","plan",
    "figure","star","box","noun","field","rest","correct","able","pound","done","beauty","drive",
    "stood","contain","front","teach","week","final","gave","green","quick","develop","ocean",
    "warm","free","minute","strong","special","mind","behind","clear","tail","produce","fact",
    "street","inch","nothing","course","stay","wheel","full","force","blue","object",
    "decide","surface","deep","moon","island","foot","system","busy","test","record","boat",
    "common","gold","possible","plane","dry","wonder","laugh","thousand","ago","ran",
    "check","game","shape","hot","miss","brought","heat","snow","tire","bring","yes",
    "distant","fill","east","paint","language","among","grand","ball","yet","wave","drop","heart",
    "present","heavy","dance","position","arm","wide","sail","material","size",
    "vary","settle","speak","weight","general","ice","matter","circle","pair","include","divide",
    "felt","perhaps","pick","sudden","count","reason","square","exact","bone","age",
    "gas","print","dead","spot","suit","current","lift","rose",
    "continue","block","chart","hat","sell","success","company","event","particular",
    "deal","swim","term","opposite","wife","shoe","shoulder","spread","arrange","camp","invent",
    "cotton","born","determine","nine","truck","noise","level","chance","gather","shop",
    "stretch","throw","shine","property","column","select","wrong","gray","repeat",
    "require","broad","prepare","salt","nose","anger","claim","continent","type","draw",
    "score","tiny","cool","practice","coast","key","method","sign","wild","solve","capital",
    "mountain","north","once","base","hear","horse","cut","sure","watch","color","face",
    "wood","main","round","turn","move","house","point","every","found","answer",
    "grow","study","learn","plant","cover","food","sun","four","state","must","show",
    "own","page","such","side","three","end","right","mean","part",
    "small","little","old","down","head","same","long","much","before","line","home",
    "being","read","where","below","name","very","bit","eye","earth","form","kind",
    "help","through","each","under","land","along","near","build","words",
    "light","idea","off","sentence","away","animal","mother","set","again","play",
    "picture","change","live","almost","many","different","room","without",
    "boy","write","sound","been","water","why","going","put",
    // 200 technology words
    "algorithm","database","function","server","network","protocol","framework","library",
    "compiler","runtime","frontend","backend","middleware","container","microservice",
    "repository","deployment","pipeline","endpoint","interface","abstraction","iteration",
    "recursion","encryption","authentication","authorization","serialization","pixel",
    "bandwidth","throughput","latency","cache","buffer","thread","process","kernel",
    "filesystem","socket","packet","router","gateway","firewall","proxy","cluster",
    "instance","virtual","module","package","dependency","version","branch","merge",
    "commit","staging","production","debug","refactor","optimize","validate","configure",
    "initialize","terminate","execute","compile","deploy","monitor","scale","provision",
    "benchmark","interrupt","overflow","underflow","callback","promise","async","await",
    "component","template","directive","selector","attribute","element","render","mount",
    "dispatch","subscribe","payload","reducer","schema","query","mutation",
    "webhook","token","session","cookie","header","request","response","status",
    "parameter","variable","constant","boolean","integer","string","array",
    "pointer","reference","garbage","collection","allocation","heap","stack","queue",
    "binary","hexadecimal","octal","unicode","encoding","decoding","parsing","lexing",
    "syntax","semantic","pragma","annotation","decorator","closure","scope","context",
    "software","hardware","firmware","platform","architecture","operating","segment",
    "transistor","register","peripheral","emulator","simulator","debugger","profiler",
    "terminal","console","dashboard","viewport","stylesheet","responsive","breakpoint",
    "gradient","opacity","transform","transition","animation","rendering","scaffold",
    "iterator","generator","constructor","destructor","prototype","inheritance","polymorphism",
    "encapsulation","singleton","observer","factory","adapter","strategy","composite",
    // 150 academic words
    "hypothesis","analysis","synthesis","evaluation","methodology","theory","empirical",
    "qualitative","quantitative","correlation","regression","deviation","variance",
    "probability","distribution","frequency","magnitude","proportion","ratio","coefficient",
    "equation","formula","theorem","axiom","postulate","conjecture","proof",
    "abstract","concrete","conceptual","theoretical","practical","fundamental","essential",
    "significant","substantial","comprehensive","preliminary","subsequent","concurrent",
    "accumulate","demonstrate","investigate","incorporate","differentiate","approximate",
    "predominant","consecutive","controversial","phenomenon","paradigm","criterion",
    "implication","perspective","ambiguous","coherent","rigorous","arbitrary","explicit",
    "implicit","inherent","intrinsic","plausible","prevalent","relevant","sufficient",
    "supplement","complement","constitute","facilitate","generate","stimulate","sustain",
    "acknowledge","elaborate","formulate","speculate","manipulate","fluctuate","interpret",
    "contribute","emphasize","underlying","mechanism","dimension",
    "structure","principle","concept","factor",
    "infer","deduce","assert","refute","critique","assess","contrast","clarify",
    "derive","extract","identify","justify","modify","obtain","resolve","summarize",
    "consequent","definitive","indicative","marginal","mutual","objective","passive",
    "rational","subjective","tentative","uniform","aggregate","dynamic","finite",
    "obscure","precise","rigid","subtle","tangible","trivial","viable","volatile",
    // 150 everyday words
    "kitchen","bicycle","rooftop","garden","window","bridge","forest","stream",
    "blanket","mirror","candle","pillow","basket","bottle","ladder","hammer",
    "jacket","pocket","tunnel","castle","market","pencil","feather","diamond",
    "umbrella","village","lantern","cottage","meadow","valley","harbor","temple",
    "carpet","curtain","chimney","pebble","sunset","breeze","thunder","shadow",
    "anchor","barrel","cradle","dagger","falcon","goblet","helmet","ivory",
    "jungle","kettle","marble","needle","orchard","palace","quiver","saddle",
    "timber","velvet","whistle","crystal","blossom","chapter","compass","dolphin",
    "eclipse","furnace","glacier","horizon","impulse","journey","kingdom",
    "mystery","nucleus","passage","quarrel","shelter","triumph","venture","weather",
    "cabinet","balcony","canyon","desert","engine","fabric","garnet","hearth",
    "insect","jasmine","kitten","locket","magnet","napkin","oyster","parcel",
    "ribbon","silver","trophy","walnut","cobalt","pasture","thicket",
    "plateau","prairie","summit","tundra","lagoon","ravine","crater",
    "sandbox","bookshop","museum","theater","stadium","airport","station","campus",
    "chapel","clinic","lounge","cellar","attic","studio","garage","terrace",
    "fountain","monument","pavilion","staircase","corridor","entrance","archway",
    "pottery","hammock","gazebo","pergola","shutter","awning","railing","gutter",
    "mantle","pantry","closet","drawer","cupboard","counter","rafter","shingle",
    "faucet","bathtub","towel","sponge","bucket","broom","shovel","wrench",
    "pliers","screwdriver","toolbox","workshop","backyard","sidewalk","mailbox","doorbell"
  ];

  function getClassicText(difficulty) {
    const texts = classicTexts[difficulty] || classicTexts.medium;
    return texts[Math.floor(Math.random() * texts.length)];
  }

  function getCodeSnippet(language) {
    const snippets = codeSnippets[language] || codeSnippets.javascript;
    return snippets[Math.floor(Math.random() * snippets.length)];
  }

  function generateWords(count) {
    const words = [];
    for (let i = 0; i < count; i++) {
      words.push(wordList[Math.floor(Math.random() * wordList.length)]);
    }
    return words.join(" ");
  }

  return { getClassicText, getCodeSnippet, generateWords };
})();
